### ISSUE TITLE
How is different than heatpack

### ISSUE THREAD

**Issue by matystl** [zackify/reactview#8]
Is this different than react-heatpack https://github.com/insin/react-heatpack

One difference I see you automaticly render component wich is nice if you want to show one component but not good if you want to prototype with react router. Wouldn't it be better to merge this 2 projects and have simple command for heatpack to render one?

**Comment by zackify** [comment]
I made this before that came out I'm pretty sure

**Comment by zackify** [comment]
added heatpack to the readme, closing
